-- Hawaii e Alaska come aree geografiche USA
-- La colonna geographic_area è VARCHAR(100) NULL, quindi accetta qualsiasi valore
-- incluso 'HAWAII' e 'ALASKA' senza ulteriori modifiche al DB.
--
-- Se in passato era ENUM, la migrazione è:
--   ALTER TABLE tours
--   MODIFY COLUMN geographic_area VARCHAR(100) NULL;
--
-- Frontend: TourEditor (Area Geografica) e DynamicTours (filtri) includono già
-- le opzioni: EST, OVEST, EST E OVEST, SOUTH, MID WEST, HAWAII, ALASKA.
